unpackaged/main/default/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&#39;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/traa_Status_Processor_Rule__mdt.object-meta.xml
<CustomObject>
    <description>Designed to automate the transition of record statuses.</description>
    <label>traa Status Processor Rule</label>
    <pluralLabel>traa Status Processor Rules</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_Field__c</fullName>
    <label>Source Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_SObject_Type__c</fullName>
    <label>Source SObject Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/traa_StatusUpdate_TDTM.cls
/**
* @description TDTM class for ProgramEnrollment trigger
*
*
* @author      Traction on Demand (Traction TRAA Package)
* @date        2020-02-19
*/
global without sharing class traa_StatusUpdate_TDTM extends hed.TDTM_Runnable{
    // the main entry point for TDTM to invoke our trigger handlers.
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
       
        if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            Map<Id, hed__Program_Enrollment__c> oldMap = new Map<Id, hed__Program_Enrollment__c>((List<hed__Program_Enrollment__c>) oldList);
            updateStatus((List<hed__Program_Enrollment__c>) newList, oldMap);
        }
        
        return dmlWrapper;
    }

    private void updateStatus(List<hed__Program_Enrollment__c> ProgramEnrollments, Map<Id, hed__Program_Enrollment__c> oldMap) {
        Set<String> fieldsToCheck = new Set<String>(getStatusProcessor());
        for(hed__Program_Enrollment__c progEnrollment : ProgramEnrollments){
            //Update related objets on update of Enrollment Status as defined in trac_Status_Processor metadata records
            Boolean runStatusProcessor = false;
            for (String fieldToCheck : fieldsToCheck) {
                if (oldMap.get(progEnrollment.Id).get(fieldToCheck) != progEnrollment.get(fieldToCheck)) {
                    runStatusProcessor = true;
                    break;
                }
            }
            if (runStatusProcessor) {
                traa_StatusProcessor.execute(ProgramEnrollments, oldMap);
            }
        }
    }

    private Set<String> getStatusProcessor() {
        Set<String> fieldsToCheck = new Set<String>();
        for (traa_Status_Processor_Rule__mdt statusProcessorRule : [SELECT Id, traa_Source_SObject_Type__c, traa_Source_Field__c FROM traa_Status_Processor_Rule__mdt WHERE traa_Source_SObject_Type__c = 'hed__Program_Enrollment__c']) {
            if(String.isNotBlank(statusProcessorRule.traa_Source_Field__c)) {
                fieldsToCheck.add(statusProcessorRule.traa_Source_Field__c);
            }
        }
        return fieldsToCheck;
    }
}