unpackaged/main/default/objects/hed__Test_Score__c/hed__Test_Score__c.object-meta.xml
<CustomObject>
    <description>The score on a section of a specific test or a composite score.</description>
    <label>Test Score</label>
    <nameField>
        <displayFormat>SCR-{0000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Test_Score__c/fields/hed__Subject_Area__c.field-meta.xml
<CustomField>
    <fullName>hed__Subject_Area__c</fullName>
    <description>The subject matter or category for this test score.</description>
    <inlineHelpText>The subject matter or category for this test score.</inlineHelpText>
    <label>Subject Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Language</fullName>
            </value>
            <value>
                <fullName>Mathematics</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Overall</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/tf_TestScoreWrapper.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Wrapper class for Test Score Record Operation
*/
public class tf_TestScoreWrapper implements tf_TestFactory.FieldDefaults{
    
    protected Type sObjectType;
    
    public Type getObjectType() {
        return hed__Test_Score__c.class;
    }
    public Map<String, Object> getFieldDefaults() {
        return new Map<String, Object> {
            'hed__Score__c' => 90
                };
                    }
    
    public Map<String, Object> getRequiredFieldDefaults() {
        return new Map<String, Object> {
            'hed__Subject_Area__c' => 'Reading'
                };
                    }
}