unpackaged/main/default/objects/hed__Test__c/hed__Test__c.object-meta.xml
<CustomObject>
    <description>An instance of a student taking a test.</description>
    <label>Test</label>
    <nameField>
        <displayFormat>TST-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Test__c/fields/hed__Test_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Test_Type__c</fullName>
    <description>The formal name for the test taken.</description>
    <inlineHelpText>The formal name for the test taken.</inlineHelpText>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>GRE</fullName>
            </value>
            <value>
                <fullName>GMAT</fullName>
            </value>
            <value>
                <fullName>TOEFL</fullName>
            </value>
            <value>
                <fullName>ACCUNEXTGEN</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>CLEP</fullName>
            </value>
            <value>
                <fullName>PERT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Test__c/fields/traa_Lead__c.field-meta.xml
<CustomField>
    <fullName>traa_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If a contact and opportunity originated from a lead, this field is used to indicate the lead record that the test record originated from.</description>
    <inlineHelpText>If a contact and opportunity originated from a lead, this field is used to indicate the lead record that the test record originated from.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>traa_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/traa_LeadTestsTransferToContact_TDTM.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     On Lead conversion any Test child records on lead should be transfer to the new or existing contact. 
For Duplicate Tests based on Test Type transfer Test Scores.
*/
global without sharing class traa_LeadTestsTransferToContact_TDTM extends hed.TDTM_Runnable {
    // the main entry point for TDTM to invoke our trigger handlers.
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        Map<Id,Lead> newLeadMap = new Map<Id,Lead>((List<Lead>) newList);
        Map<Id, List<hed__Test__c>> leadIdToTestsMap = new Map<Id, List<hed__Test__c>>();
        Map<Id, Id> leadIdToContactIdMap = new Map<Id, Id>();
        List<hed__Test__c> testsToBeUpdated = new List<hed__Test__c>();

        if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            Map<Id, Lead> oldLeadMap = new Map<Id, Lead>((List<Lead>)oldList);
            
            for(Lead lead : [SELECT Id, convertedContactId, (SELECT Id, Name, hed__Test_Type__c, hed__Contact__c FROM traa_Tests__r) FROM Lead WHERE Id IN : newLeadMap.keySet()]){
                if (oldLeadMap.containsKey(lead.Id) && newLeadMap.containsKey(lead.Id)) {
                    //Check if the Lead is Converted
                    if (isLeadConverted(newLeadMap.get(lead.Id), oldLeadMap)) {
                        if(lead.traa_Tests__r.size()>0){
                            //Collect Lead Id and Related Test Records
                            for(hed__Test__c test : lead.traa_Tests__r){
                                if(!leadIdToTestsMap.containsKey(lead.Id)){
                                    leadIdToTestsMap.put(lead.Id, new List<hed__Test__c>());
                                }
                                leadIdToTestsMap.get(lead.Id).add(test);
                            }
                            //Collect Lead Id and Converted Contact Id
                            leadIdToContactIdMap.put(lead.Id, lead.ConvertedContactId);
                        }
                    }
                }
            }
            
            for(Id leadId : leadIdToTestsMap.keySet()){
                List<hed__Test__c> leadTests= leadIdToTestsMap.get(leadId);
                for(hed__Test__c leadTest : leadTests){
                    leadTest.hed__Contact__c = leadIdToContactIdMap.get(leadId);
                    testsToBeUpdated.add(leadTest);
                }
                
            }
            
        }
        if(testsToBeUpdated.size()>0){
            dmlWrapper.objectsToUpdate.addAll((List<SObject>) testsToBeUpdated);
        }
        
        return dmlWrapper;
        
    }

    private Boolean isLeadConverted(Lead lead, Map<Id, Lead> oldMap) {
        return(oldMap != null && lead.Status != oldMap.get(lead.Id).Status && lead.IsConverted);
    }
}