unpackaged/main/default/objects/hed__Test__c/hed__Test__c.object-meta.xml
<CustomObject>
    <description>An instance of a student taking a test.</description>
    <label>Test</label>
    <nameField>
        <displayFormat>TST-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Test__c/fields/hed__Test_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Test_Type__c</fullName>
    <description>The formal name for the test taken.</description>
    <inlineHelpText>The formal name for the test taken.</inlineHelpText>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>GRE</fullName>
            </value>
            <value>
                <fullName>GMAT</fullName>
            </value>
            <value>
                <fullName>TOEFL</fullName>
            </value>
            <value>
                <fullName>ACCUNEXTGEN</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>CLEP</fullName>
            </value>
            <value>
                <fullName>PERT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/tf_TestWrapper.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Wrapper class for Test Record Operation
*/
public class tf_TestWrapper implements tf_TestFactory.FieldDefaults{
    
    protected Type sObjectType;
    
    public Type getObjectType() {
        return hed__Test__c.class;
    }
    public Map<String, Object> getFieldDefaults() {
        return new Map<String, Object> {
            'hed__Source__c' => 'Official'
                };
                    }
    
    public Map<String, Object> getRequiredFieldDefaults() {
        return new Map<String, Object> {
            'hed__Test_Type__c' => 'GRE',
                'hed__Test_Date__c' => System.today()
                };
                    }
}