unpackaged/main/default/objects/Account/fields/Decision_Type__c.field-meta.xml
<CustomField>
    <fullName>Decision_Type__c</fullName>
    <description>Determines how the Applicant Facing Status will be updated on the application</description>
    <inlineHelpText>Determines how the Applicant Facing Status will be updated on the application</inlineHelpText>
    <label>Decision Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rolling</fullName>
            </value>
            <value>
                <fullName>Update on Publish Decision Date</fullName>
            </value>
            <value>
                <fullName>Manual Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/traa_Publish_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>traa_Publish_Decision_Date__c</fullName>
    <description>Used to identify the academic program this year is apart of.</description>
    <inlineHelpText>Used to identify the academic program this year is apart of.</inlineHelpText>
    <label>Publish Decision Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/hed__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Application_Status__c</fullName>
    <description>The status of the application process.</description>
    <inlineHelpText>The status of the application process.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Publish_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>traa_Publish_Decision_Date__c</fullName>
    <description>Used to identify the academic program this  year is apart of.</description>
    <formula>hed__Applying_To__r.traa_Publish_Decision_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used to identify the academic program this  year is apart of.</inlineHelpText>
    <label>Publish Decision Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/traa_ApplicationDecisionDatePassedTest.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Test Class for traa_ApplicationDecisionDatePassed
*/
@isTest
public class traa_ApplicationDecisionDatePassedTest {
    
    // Dummy CRON expression: midnight on April 9.
    public static String CRON_EXP = '0 0 0 09 4 ?';
    
    @isTest
    private static void applicationDecisionDatePassedTest(){
        
        //Create Account Record
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        Date decisionDate = System.today();
        Map<String, Object> academicProgramAdditionalFields = new Map<String, Object>{
            'RecordTypeId'                  => recordTypeId,
             'traa_Publish_Decision_Date__c' => decisionDate,
             'Decision_Type__c'             => traa_Constants.ACCOUNT_DECISION_STAGE_UPDATE_ON_PUBLISH_DATE
                };
                    
                    //Create Academic Program Record 
                    Account academicProgram = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,  academicProgramAdditionalFields, true);
        
        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
            'AccountId'       => academicProgram.Id
                };
                    
                    //Create Contact Record
                    Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);
        
        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
            'hed__Applicant__c'       => contact.Id,
                'hed__Applying_To__c'    => academicProgram.Id
                
                };     
                    
                    //Create Application Record
        hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class,  applicationAdditionalFields, true);
        application.hed__Application_Status__c = 'Accepted';
        update application;
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new traa_ApplicationDecisionDatePassed());
        // Stopping the test will run the job synchronously
        Test.stopTest();

        AsyncApexJob results = [SELECT JobType, Status, NumberOfErrors FROM AsyncApexJob LIMIT 1];
        System.assertEquals('ScheduledApex', results.JobType,'Incorrect Job type returned');
        System.assertEquals('Queued',results.Status, 'Status or returned job is incorrect');
        System.assertEquals(0,results.NumberOfErrors,'Job returned errors');
    }
}