unpackaged/main/default/objects/Account/fields/Decision_Type__c.field-meta.xml
<CustomField>
    <fullName>Decision_Type__c</fullName>
    <description>Determines how the Applicant Facing Status will be updated on the application</description>
    <inlineHelpText>Determines how the Applicant Facing Status will be updated on the application</inlineHelpText>
    <label>Decision Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rolling</fullName>
            </value>
            <value>
                <fullName>Update on Publish Decision Date</fullName>
            </value>
            <value>
                <fullName>Manual Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/hed__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Application_Status__c</fullName>
    <description>The status of the application process.</description>
    <inlineHelpText>The status of the application process.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Applicant_Facing_Status__c.field-meta.xml
<CustomField>
    <fullName>traa_Applicant_Facing_Status__c</fullName>
    <description>This field is to show the status of the application to the applicant (In case they are accepted or rejected but you do not want them to know the decision yet)</description>
    <inlineHelpText>This field is to show the status of the application to the applicant (In case they are accepted or rejected but you do not want them to know the decision yet)</inlineHelpText>
    <label>Applicant Facing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Accepted Offer</fullName>
                <isActive>false</isActive>
                <label>Accepted Offer</label>
            </value>
            <value>
                <fullName>Declined Offer</fullName>
                <isActive>false</isActive>
                <label>Declined Offer</label>
            </value>
            <value>
                <fullName>Deferred Offer</fullName>
                <isActive>false</isActive>
                <label>Deferred Offer</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <isActive>false</isActive>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Waitlist</fullName>
                <isActive>false</isActive>
                <label>Waitlist</label>
            </value>
            <value>
                <fullName>What</fullName>
                <isActive>false</isActive>
                <label>What</label>
            </value>
            <value>
                <fullName>When</fullName>
                <isActive>false</isActive>
                <label>When</label>
            </value>
            <value>
                <fullName>Where</fullName>
                <isActive>false</isActive>
                <label>Where</label>
            </value>
            <value>
                <fullName>Who</fullName>
                <isActive>false</isActive>
                <label>Who</label>
            </value>
            <value>
                <fullName>Why</fullName>
                <isActive>false</isActive>
                <label>Why</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/traa_UpdateFacingStatus_TDTMTest.cls
/**
*******************************************************************************************
* @author, Traction on Demand (Traction TRAA Package)
* @description this test class contains methods to test the methods of traa_UpdateFacingStatus_TDTM class
* @date 2020-04-08
*
*******************************************************************************************
*/
@IsTest
public class traa_UpdateFacingStatus_TDTMTest {
    @IsTest
    private static void updateFacingStatusTest(){
        
        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        
        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_UpdateFacingStatus_TDTM', 'Application__c', 'AfterUpdate', 1.00));
        
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        
        //Create Academic program Record
        Map<String, Object> academicProgramAdditionalFields = new Map<String, Object>{
            'RecordTypeId' => recordTypeId,
            'Decision_Type__c' => traa_Constants.ACCOUNT_DECISION_STAGE_ROLLING
                };
                    Account account = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,academicProgramAdditionalFields,  true);
        
        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
            'AccountId'       => account.Id
                };
                    
                    //Create Contact Record
                    Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);
        
        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
            'hed__Applicant__c'       => contact.Id,
             'hed__Applying_To__c'    => account.Id,
              'hed__Application_Status__c' =>'Received'
                };     
                    //Create Application Record
                    hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class,  applicationAdditionalFields, true);
        
        //Update Application Record
        application.hed__Application_Status__c = 'What';
        Test.startTest();
        update application;
        Test.stopTest();
        hed__Application__c updatedApplication = [SELECT Id, hed__Application_Status__c, traa_Applicant_Facing_Status__c FROM hed__Application__c WHERE Id =:application.Id];
        System.assertEquals(updatedApplication.traa_Applicant_Facing_Status__c, updatedApplication.hed__Application_Status__c, 'Application Facing Status is Updated');
    }
    
    @IsTest
    private static void updateFacingStatusOnUpdateTest(){
        
        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        
        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_UpdateFacingStatus_TDTM', 'Application__c', 'AfterUpdate', 1.00));
        
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        
        //Create Academic program Record
        Map<String, Object> academicProgramAdditionalFields = new Map<String, Object>{
            'RecordTypeId' => recordTypeId,
            'Decision_Type__c' => traa_Constants.ACCOUNT_DECISION_STAGE_ROLLING
                };
                    Account account = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,academicProgramAdditionalFields,  true);
        
        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
            'AccountId'       => account.Id
                };
                    
                    //Create Contact Record
                    Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);
        
        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
            'hed__Applicant__c'       => contact.Id,
             'hed__Applying_To__c'    => account.Id
                };     
                    
                    //Create Application Record
                    hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class,  applicationAdditionalFields, true);
        
        //Update Application Record
        application.hed__Application_Status__c = 'Who';
        Test.startTest();
        update application;
        Test.stopTest();
        
        hed__Application__c updatedApplication = [SELECT Id, hed__Application_Status__c, traa_Applicant_Facing_Status__c FROM hed__Application__c WHERE Id =:application.Id];
        System.assertEquals(updatedApplication.traa_Applicant_Facing_Status__c, updatedApplication.hed__Application_Status__c, 'Application Facing Status is Updated');
    }

    @IsTest
    private static void updateFacingStatusOnCreateTest(){

        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_UpdateFacingStatus_TDTM', 'Application__c', 'AfterInsert', 1.00));

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();

        //Create Academic program Record
        Map<String, Object> academicProgramAdditionalFields = new Map<String, Object>{
                'RecordTypeId' => recordTypeId,
                'Decision_Type__c' => traa_Constants.ACCOUNT_DECISION_STAGE_ROLLING
        };
        Account account = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,academicProgramAdditionalFields,  true);

        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
                'AccountId'       => account.Id
        };

        //Create Contact Record
        Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);

        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
                'hed__Applicant__c'       => contact.Id,
                'hed__Applying_To__c'    => account.Id,
                'hed__Application_Status__c' => 'When'
        };

        //Create Application Record
        hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class,  applicationAdditionalFields, true);

        Test.startTest();
        update application;
        Test.stopTest();

        hed__Application__c updatedApplication = [SELECT Id, hed__Application_Status__c, traa_Applicant_Facing_Status__c FROM hed__Application__c WHERE Id =:application.Id];
        System.assertEquals(updatedApplication.traa_Applicant_Facing_Status__c, updatedApplication.hed__Application_Status__c, 'Application Facing Status is Updated');
    }
}