unpackaged/main/default/objects/Account/fields/traa_Application_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>traa_Application_Record_Types__c</fullName>
    <label>Application Record Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDA Application</fullName>
            </value>
            <value>
                <fullName>Academic Application</fullName>
                <default>true</default>
                <label>Academic Application</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/hed__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Application_Status__c</fullName>
    <description>The status of the application process.</description>
    <inlineHelpText>The status of the application process.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>traa_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity Record</description>
    <inlineHelpText>Lookup to Opportunity Record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Secondary_Program_Applying_To__c.field-meta.xml
<CustomField>
    <fullName>traa_Secondary_Program_Applying_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>In case of Dual Degree, it represent the dual degree secondary academic program or  major the applicant is applying to</inlineHelpText>
    <label>Secondary Program Applying To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Secondary Program Applying To)</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Applicant__c.field-meta.xml
<CustomField>
    <fullName>traa_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact record of the applicant</description>
    <inlineHelpText>Lookup to the contact record of the applicant</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Dual_Degree_Sec_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Dual_Degree_Sec_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the secondary Academic Program, in case of dual degree program during application.</inlineHelpText>
    <label>Dual Degree Secondary Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dual Sec: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>traa_Secondary_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Application__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Application Record</description>
    <inlineHelpText>Will display admission application details from Application System if available</inlineHelpText>
    <label>Primary Application</label>
    <referenceTo>hed__Application__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/traa_UpdateAppApplyingToOnOpp_TDTM_Test.cls
/**
 * Unit tests for the traa_UpdateAppApplyingToBasedOnOpp_TDTM class.
 *
 * @author Pranshu Sharma, Traction on Demand
 * @date   2021-05-21
 */

@IsTest
private class traa_UpdateAppApplyingToOnOpp_TDTM_Test {
    @testSetup
    static void testData() {
        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_UpdateAppApplyingToBasedOnOpp_TDTM', 'Opportunity',
                'AfterUpdate', 1.00));

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
    }

    @IsTest
    static void testUpdateAppApplyingToBasedOnOpp_TDTM() {

        Id recordTypeIdAcc = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        List<Account> accountList = (List<Account>) tf_TestFactory.createSObjectList(2,tf_AccountWrapper.class, new Map<String, Object>{
                'traa_Application_Record_Types__c' => traa_Constants.RT_ACADEMIC_APPLICATION,
                'RecordTypeId' => recordTypeIdAcc
        }, true);

        Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, new Map<String, Object>{
                'AccountId' => accountList[0].Id
        }, true);
        Map<String, Object> opportunityAdditionalFields = new Map<String, Object>{
                'traa_Applicant__c' => contact.Id,
                'traa_Academic_Program__c' => accountList[0].Id,
                'traa_Dual_Degree_Sec_Academic_Program__c' => accountList[1].Id
        };

        Opportunity opportunity = (Opportunity) tf_TestFactory.createSObject(tf_OpportunityWrapper.class, opportunityAdditionalFields, true);
        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
                'hed__Applicant__c' => contact.Id,
                'hed__Applying_To__c' => accountList[0].Id,
                'traa_Secondary_Program_Applying_To__c' => accountList[1].Id,
                'hed__Application_Status__c' => 'Received',
                'traa_Opportunity__c' => opportunity.Id
        };
        //Create Application Record
        hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class,  applicationAdditionalFields, true);

        Test.startTest();
        opportunity.traa_Primary_Application__c = application.Id;
        opportunity.traa_Academic_Program__c = accountList[1].Id;
        opportunity.traa_Dual_Degree_Sec_Academic_Program__c = accountList[0].Id;
        update opportunity;
        Test.stopTest();
        hed__Application__c updatedApplication = [SELECT hed__Applying_To__c, traa_Secondary_Program_Applying_To__c FROM hed__Application__c WHERE Id = :application.Id];
        System.assertNotEquals(updatedApplication.hed__Applying_To__c, updatedApplication.traa_Secondary_Program_Applying_To__c,'Both Applying To and Secondary Program Applying To can not be same.');
        System.assertEquals(updatedApplication.hed__Applying_To__c, opportunity.traa_Academic_Program__c,'Applying to should be updated to match with opportunity Academic Program');
        System.assertEquals(updatedApplication.traa_Secondary_Program_Applying_To__c,opportunity.traa_Dual_Degree_Sec_Academic_Program__c,'Secondary Program Applying to should be updated to match with opportunity Dual Degree Secondary Academic Program');
    }
}