unpackaged/main/default/objects/Account/fields/traa_Application_Deadline__c.field-meta.xml
<CustomField>
    <fullName>traa_Application_Deadline__c</fullName>
    <description>Application submission deadline</description>
    <inlineHelpText>Application submission deadline</inlineHelpText>
    <label>Application Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Academic_Program.recordType-meta.xml
<RecordType>
    <fullName>Academic_Program</fullName>
    <active>true</active>
    <description>An Academic Program offered at the educational institution.</description>
    <label>Academic Program</label>
</RecordType>

unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Application_Deadline__c.field-meta.xml
<CustomField>
    <fullName>traa_Application_Deadline__c</fullName>
    <description>Application submission deadline</description>
    <inlineHelpText>Application submission deadline</inlineHelpText>
    <label>Application Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>traa_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity Record</description>
    <inlineHelpText>Lookup to Opportunity Record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Secondary_Program_Applying_To__c.field-meta.xml
<CustomField>
    <fullName>traa_Secondary_Program_Applying_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>In case of Dual Degree, it represent the dual degree secondary academic program or  major the applicant is applying to</inlineHelpText>
    <label>Secondary Program Applying To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Secondary Program Applying To)</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Decision_Notes__c.field-meta.xml
<CustomField>
    <fullName>traa_Decision_Notes__c</fullName>
    <description>Used to specify decisions if &quot;Declined Reason&quot; picklist is Other</description>
    <inlineHelpText>Used to specify decisions if &quot;Declined Reason&quot; picklist is Other</inlineHelpText>
    <label>Decision Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Declined_Reason__c.field-meta.xml
<CustomField>
    <fullName>traa_Declined_Reason__c</fullName>
    <description>Reason applicant declined an offer</description>
    <inlineHelpText>Reason applicant declined an offer</inlineHelpText>
    <label>Declined Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finances</fullName>
            </value>
            <value>
                <fullName>Timing</fullName>
            </value>
            <value>
                <fullName>Competitor University</fullName>
            </value>
            <value>
                <fullName>Indecisive</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Application__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Application Record</description>
    <inlineHelpText>Will display admission application details from Application System if available</inlineHelpText>
    <label>Primary Application</label>
    <referenceTo>hed__Application__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/traa_AccApplicationDeadlinePassed.cls
/*
* @author          Traction on Demand
* @description     Class to check Account - Academic Program Record, When it reaches to its Application Deadline. If so,
                   Then sets its child Opportunities to Closed Lost Stage, if they do not have an application child record.
*/
global without sharing class traa_AccApplicationDeadlinePassed implements Schedulable  {
    global void execute(SchedulableContext ctx) {
        
        Set<Id> opportunityIds = new Set<Id>();
        List<Opportunity> oppToBeUpdated = new List<Opportunity>();
        
        //Get Academic Program Record Type of Account
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Academic_Program').getRecordTypeId();
        
        //Collect related Opportunities when Account's Application Deadline is passed
        Date todayDate = System.today();
        for(Account account : [SELECT Id, (SELECT Id FROM traa_Opportunities__r) FROM Account WHERE traa_Application_Deadline__c <> null AND traa_Application_Deadline__c = : todayDate AND RecordTypeId = :recordTypeId]){
            if(account.traa_Opportunities__r.size() > 0){
                for(Opportunity opp : account.traa_Opportunities__r){
                    opportunityIds.add(opp.id);
                }
            }
        }
        //Update Opportunities which don't have related applications
        if(!opportunityIds.isEmpty()){
            for(Opportunity opportunity : [SELECT Id, (SELECT Id FROM traa_Applications__r) FROM Opportunity WHERE Id IN :opportunityIds]){
                if(opportunity.traa_Applications__r.isEmpty()){
                    opportunity.StageName = traa_Constants.STAGE_NAME_STALE;
                    opportunity.traa_Declined_Reason__c = traa_Constants.DECLINED_REASON_OTHER;
                    opportunity.traa_Decision_Notes__c = traa_Constants.DECLINED_NOTES;
                    oppToBeUpdated.add(opportunity);
                }
            }
            if(!oppToBeUpdated.isEmpty()){
                update oppToBeUpdated;
            }
        }
    }
}