unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/hed__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Application_Status__c</fullName>
    <description>The status of the application process.</description>
    <inlineHelpText>The status of the application process.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Applicant_Facing_Status__c.field-meta.xml
<CustomField>
    <fullName>traa_Applicant_Facing_Status__c</fullName>
    <description>This field is to show the status of the application to the applicant (In case they are accepted or rejected but you do not want them to know the decision yet)</description>
    <inlineHelpText>This field is to show the status of the application to the applicant (In case they are accepted or rejected but you do not want them to know the decision yet)</inlineHelpText>
    <label>Applicant Facing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Info</fullName>
                <default>true</default>
                <label>Personal Info</label>
            </value>
            <value>
                <fullName>Start Term</fullName>
            </value>
            <value>
                <fullName>Campus / Location</fullName>
            </value>
            <value>
                <fullName>Program/Major</fullName>
            </value>
            <value>
                <fullName>Academic History</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Accepted Offer</fullName>
                <isActive>false</isActive>
                <label>Accepted Offer</label>
            </value>
            <value>
                <fullName>Declined Offer</fullName>
                <isActive>false</isActive>
                <label>Declined Offer</label>
            </value>
            <value>
                <fullName>Deferred Offer</fullName>
                <isActive>false</isActive>
                <label>Deferred Offer</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <isActive>false</isActive>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Waitlist</fullName>
                <isActive>false</isActive>
                <label>Waitlist</label>
            </value>
            <value>
                <fullName>What</fullName>
                <isActive>false</isActive>
                <label>What</label>
            </value>
            <value>
                <fullName>When</fullName>
                <isActive>false</isActive>
                <label>When</label>
            </value>
            <value>
                <fullName>Where</fullName>
                <isActive>false</isActive>
                <label>Where</label>
            </value>
            <value>
                <fullName>Who</fullName>
                <isActive>false</isActive>
                <label>Who</label>
            </value>
            <value>
                <fullName>Why</fullName>
                <isActive>false</isActive>
                <label>Why</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/traa_Status_Processor_Rule__mdt.object-meta.xml
<CustomObject>
    <description>Designed to automate the transition of record statuses.</description>
    <label>traa Status Processor Rule</label>
    <pluralLabel>traa Status Processor Rules</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Check_Special_Condition__c.field-meta.xml
<CustomField>
    <fullName>traa_Check_Special_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Extra field which can be used by objects for their any special condition</inlineHelpText>
    <label>Check Special Condition</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_Field__c</fullName>
    <label>Source Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_SObject_Type__c</fullName>
    <label>Source SObject Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_Value__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_Value__c</fullName>
    <label>Source Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Target_Reference__c.field-meta.xml
<CustomField>
    <fullName>traa_Target_Reference__c</fullName>
    <label>Target Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/traa_UpdateFacingStatus_TDTM.cls
/**
*******************************************************************************************
* @author, Traction on Demand (Traction TRAA Package)
* @description Contains all the queries related to Application Object
* @date 2020-04-08
*
*******************************************************************************************
*/

global without sharing class traa_UpdateFacingStatus_TDTM extends hed.TDTM_Runnable {
    // the main entry point for TDTM to invoke our trigger handlers.

    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

        //update Applicant Facing Status with Applicaiton Status by calling status processor when
        //traa_Status_Processor_Rule__mdt record has Check_Special_Condition__c flag set as true
        //or Decision Type is selected as Rolling in Academic Program record.

        if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {

            Map<String, traa_Status_Processor_Rule__mdt> statusProcessorRulesByValue = getMetaDataRules();
            List<traa_Status_Processor_Rule__mdt> statusProcessorRules = [SELECT Id, traa_Source_SObject_Type__c, traa_Source_Field__c FROM traa_Status_Processor_Rule__mdt WHERE traa_Source_SObject_Type__c =: traa_Constants.ST_APPLICATIONS];
            Map<Id, hed__Application__c> oldApplicationMap = new Map<Id, hed__Application__c>((List<hed__Application__c>) oldList);
            Map<Id, hed__Application__c> applicationMap = new Map<Id, hed__Application__c>([SELECT Id,hed__Applying_To__r.Decision_Type__c FROM hed__Application__c WHERE Id IN :oldApplicationMap.keySet()]);
            Map<Id, String> decisionTypeMap = new Map<Id, String>();
            for (hed__Application__c application : applicationMap.values()) {
                decisionTypeMap.put(application.Id, application.hed__Applying_To__r.Decision_Type__c);
            }
            Set<String> fieldsToCheck = new Set<String>();
            for (traa_Status_Processor_Rule__mdt statusProcessorRule : statusProcessorRules) {
                fieldsToCheck.add(statusProcessorRule.traa_Source_Field__c);
            }
            for (hed__Application__c application : (List<hed__Application__c>) newList) {

                Boolean runStatusProcessor = false;
                for (String fieldToCheck : fieldsToCheck) {
                    if (oldApplicationMap.get(application.Id).get(fieldToCheck) != application.get(fieldToCheck)) {
                        runStatusProcessor = true;
                        break;
                    }
                }
                if (runStatusProcessor) {

                    if (!statusProcessorRulesByValue.containsKey(application.hed__Application_Status__c)
                            || statusProcessorRulesByValue.get(application.hed__Application_Status__c).traa_Check_Special_Condition__c
                            || decisionTypeMap.get(application.Id) == traa_Constants.ACCOUNT_DECISION_STAGE_ROLLING) {
                        //this will call traa_Status_Processor_Rule__mdt metadata and will assign hed__Application_Status__c to traa_Applicant_Facing_Status__c

                        traa_StatusProcessor.execute(newList, oldApplicationMap);
                    }
                }

            }
        }
        else if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert) {
            List<traa_Status_Processor_Rule__mdt> statusProcessorRules = [SELECT Id, traa_Source_SObject_Type__c, traa_Source_Field__c FROM traa_Status_Processor_Rule__mdt WHERE traa_Source_SObject_Type__c =: traa_Constants.ST_APPLICATIONS];

            Set<String> fieldsToCheck = new Set<String>();
            for (traa_Status_Processor_Rule__mdt statusProcessorRule : statusProcessorRules) {
                fieldsToCheck.add(statusProcessorRule.traa_Source_Field__c);
            }
            for (hed__Application__c application : (List<hed__Application__c>) newList) {

                Boolean runStatusProcessor = false;
                for (String fieldToCheck : fieldsToCheck) {
                    if (application.get(fieldToCheck) != null) {
                        runStatusProcessor = true;
                        break;
                    }
                }
                if (runStatusProcessor) {
                    traa_StatusProcessor.execute(newList, null);
                }

            }

        }

        return dmlWrapper;
    }
    /**
	* @description Queries traa_Status_Processor_Rule__mdt records for hed_Application__c object
	* @return Map<String,Boolean>, map containing Source value and check special Condition field of status processor
	*/
    private Map<String, traa_Status_Processor_Rule__mdt> getMetaDataRules() {
        List<traa_Status_Processor_Rule__mdt> rulesList = [
                SELECT Id,traa_Source_Value__c, traa_Source_Field__c, traa_Check_Special_Condition__c, traa_Target_Reference__c
                FROM traa_Status_Processor_Rule__mdt
                WHERE traa_Source_SObject_Type__c = :traa_Constants.ST_APPLICATIONS
        ];
        Map<String, traa_Status_Processor_Rule__mdt> statusProcessorRules = new Map<String, traa_Status_Processor_Rule__mdt>();
        for (traa_Status_Processor_Rule__mdt rule : rulesList) {
            statusProcessorRules.put(rule.traa_Source_Value__c, rule);
        }
        return statusProcessorRules;
    }
}