unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>traa_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity Record</description>
    <inlineHelpText>Lookup to Opportunity Record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Secondary_Program_Applying_To__c.field-meta.xml
<CustomField>
    <fullName>traa_Secondary_Program_Applying_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>In case of Dual Degree, it represent the dual degree secondary academic program or  major the applicant is applying to</inlineHelpText>
    <label>Secondary Program Applying To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Secondary Program Applying To)</relationshipLabel>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Dual_Degree_Sec_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Dual_Degree_Sec_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the secondary Academic Program, in case of dual degree program during application.</inlineHelpText>
    <label>Dual Degree Secondary Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dual Sec: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>traa_Secondary_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Application__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Application Record</description>
    <inlineHelpText>Will display admission application details from Application System if available</inlineHelpText>
    <label>Primary Application</label>
    <referenceTo>hed__Application__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/traa_UpdateAppApplyingToBasedOnOpp_TDTM.cls
/**
 * @description: Updates Application's Applying To And Secondary Applying To based on Opportunity field traa_Academic_Program__c and traa_Dual_Degree_Sec_Academic_Program__c update
 *
 * @author Pranshu Sharma, Traction on Demand
 * @date   2021-05-21
 */

global inherited sharing class traa_UpdateAppApplyingToBasedOnOpp_TDTM extends hed.TDTM_Runnable {
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>((List<Opportunity>) oldList);
            List<hed__Application__c> updatedApplications = new List<hed__Application__c>();
            updatedApplications = updatePrimaryAndSecondaryProgram((List<Opportunity>) newList, oldMap);
            dmlWrapper.objectsToUpdate.addAll((List<SObject>) updatedApplications);
        }
        return dmlWrapper;
    }

    private List<hed__Application__c> updatePrimaryAndSecondaryProgram(List<Opportunity> opportunities, Map<Id, Opportunity> oldMap) {
        Map<Id, Opportunity> opportunitiesAcademicProgramUpdated = new Map<Id, Opportunity>();
        List<hed__Application__c> updatedApplications = new List<hed__Application__c>();
        for (Opportunity opportunity : opportunities) {
            if (String.isNotBlank(opportunity.traa_Primary_Application__c) && ((String.isNotBlank(opportunity.traa_Academic_Program__c) && isAcademicProgramChanged(opportunity, oldMap))
                    || (String.isNotBlank(opportunity.traa_Academic_Program__c) && String.isNotBlank(opportunity.traa_Dual_Degree_Sec_Academic_Program__c) && isDualAcademicProgramChanged(opportunity, oldMap)))) {
                opportunitiesAcademicProgramUpdated.put(opportunity.Id, opportunity);
            }
        }

        if(!opportunitiesAcademicProgramUpdated.isEmpty()) {
            Map<Id, hed__Application__c> applicationsByIds = new Map<Id, hed__Application__c>(getApplications(opportunitiesAcademicProgramUpdated.keySet()));
            for (hed__Application__c application : applicationsByIds.values()) {
                if (opportunitiesAcademicProgramUpdated.containsKey(application.traa_Opportunity__c) && application.Id == opportunitiesAcademicProgramUpdated.get(application.traa_Opportunity__c).traa_Primary_Application__c) {
                    if (application.hed__Applying_To__c != opportunitiesAcademicProgramUpdated.get(application.traa_Opportunity__c).traa_Academic_Program__c) {
                        application.hed__Applying_To__c = opportunitiesAcademicProgramUpdated.get(application.traa_Opportunity__c).traa_Academic_Program__c;
                        updatedApplications.add(application);
                    }
                    if (application.traa_Secondary_Program_Applying_To__c != opportunitiesAcademicProgramUpdated.get(application.traa_Opportunity__c).traa_Dual_Degree_Sec_Academic_Program__c) {
                        application.traa_Secondary_Program_Applying_To__c = opportunitiesAcademicProgramUpdated.get(application.traa_Opportunity__c).traa_Dual_Degree_Sec_Academic_Program__c;
                        updatedApplications.add(application);
                    }
                }
            }
        }
        return updatedApplications;
    }

    private List<hed__Application__c> getApplications(Set<Id> opportunityIds) {
        List<hed__Application__c> applications = new List<hed__Application__c>([SELECT Id, traa_Opportunity__c, hed__Applying_To__c, traa_Secondary_Program_Applying_To__c FROM hed__Application__c WHERE traa_Opportunity__c IN : opportunityIds]);
        return applications;
    }

    private Boolean isAcademicProgramChanged(Opportunity opportunity,  Map<Id, Opportunity> oldMap) {
        return (oldMap != null && opportunity.traa_Academic_Program__c != oldMap.get(opportunity.Id).traa_Academic_Program__c);
    }

    private Boolean isDualAcademicProgramChanged(Opportunity opportunity,  Map<Id, Opportunity> oldMap) {
        return (oldMap != null && opportunity.traa_Dual_Degree_Sec_Academic_Program__c != oldMap.get(opportunity.Id).traa_Dual_Degree_Sec_Academic_Program__c);
    }
}