unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Application_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>traa_Application_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who edits Application score</description>
    <inlineHelpText>User who edits Application score</inlineHelpText>
    <label>Application Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Score__c.field-meta.xml
<CustomField>
    <fullName>traa_Score__c</fullName>
    <description>The Score of the application</description>
    <inlineHelpText>The Score of the application</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/traa_ApplicationReviewerUpdation_TDTM.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Trigger to stamp the user who edits the Application Score field
*/
global without sharing class traa_ApplicationReviewerUpdation_TDTM extends hed.TDTM_Runnable{
    // the main entry point for TDTM to invoke our trigger handlers.
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        List<hed__Application__c> applications = new List<hed__Application__c>();
        List<hed__Application__c> applicationList = new List<hed__Application__c>();
        
        if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert) {
            for (hed__Application__c application : (List<hed__Application__c>) newList) {
                if(application.traa_Score__c != null){
                    //Collect application records
                    applicationList.add(application);                   
                }
               
            }
            
        }
        else{
            if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
                Map<Id, hed__Application__c> oldApplicationMap = new Map<Id, hed__Application__c>((List<hed__Application__c>) oldList);
                
                for (hed__Application__c application : (List<hed__Application__c>) newList) {
                    if(application.traa_Score__c != null && oldApplicationMap.get(application.Id).traa_Score__c != application.traa_Score__c){
                        //Collect application records
                        applicationList.add(application);
                    }
                   
                }
                
            }
        }
        //Get Applications to update
        if(applicationList.size()>0){
            applications = updateApplications(applicationList);
            dmlWrapper.objectsToUpdate.addAll((List<SObject>) applications);
        }
        return dmlWrapper;
    }
    
    //stamp the user who edits the Application Score field
    private List<hed__Application__c> updateApplications(List<hed__Application__c> applicationList){
        List<hed__Application__c> applicationsToUpdate = new List<hed__Application__c>();
        //Set Application Reviewer who updated Application Score
        for (hed__Application__c application : applicationList){
            hed__Application__c newApplication = new hed__Application__c(Id = application.Id, traa_Application_Reviewer__c = application.LastModifiedById  );
            applicationsToUpdate.add(newApplication);
        }        
        return applicationsToUpdate;
    }
}