unpackaged/main/default/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&#39;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Application_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>traa_Application_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who edits Application score</description>
    <inlineHelpText>User who edits Application score</inlineHelpText>
    <label>Application Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>traa_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Application__c/fields/traa_Score__c.field-meta.xml
<CustomField>
    <fullName>traa_Score__c</fullName>
    <description>The Score of the application</description>
    <inlineHelpText>The Score of the application</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/traa_ApplicationReviewerUpdationTDTMTest.cls
/*
* @author          Traction on Demand (Traction traa Package)
* @description     Test class for traa_ApplicationReviewerUpdation_TDTM
*/
@isTest
public class traa_ApplicationReviewerUpdationTDTMTest {
    @isTest
    private static void applicationReviewerTest() {

//Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

//Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_ApplicationReviewerUpdation_TDTM', 'Application__c', 'AfterInsert;AfterUpdate', 1.00));

// Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

//Create Account Record
        Account account = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class, true);

        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
                'AccountId' => account.Id
        };

//Create Contact Record
        Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);

        Map<String, Object> applicationAdditionalFields = new Map<String, Object>{
                'hed__Applicant__c' => contact.Id,
                'hed__Applying_To__c' => account.Id,
                'traa_Score__c' => 1000
        };

//Create Application Record
        test.startTest();
        hed__Application__c application = (hed__Application__c) tf_TestFactory.createSObject(tf_ApplicationWrapper.class, applicationAdditionalFields, true);
        test.stopTest();

        hed__Application__c insertedApplication = [SELECT Id, traa_Application_Reviewer__c, LastModifiedById from hed__Application__c WHERE Id = :application.Id];
        System.assertEquals(insertedApplication.traa_Application_Reviewer__c, insertedApplication.LastModifiedById, 'Application Reviewer is not Populated');

//Update Application Record
        application.traa_Score__c = 1100;
        update application;

        hed__Application__c updatedApplication = [SELECT Id, traa_Application_Reviewer__c, LastModifiedById from hed__Application__c WHERE Id = :application.Id];
        System.assertEquals(updatedApplication.traa_Application_Reviewer__c, updatedApplication.LastModifiedById, 'Application Reviewer is not Updated');
    }
}