unpackaged/main/default/objects/hed__Affiliation__c/hed__Affiliation__c.object-meta.xml
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Affiliation__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Indicates whether this is a current or former Affiliation.</description>
    <inlineHelpText>Indicates whether this is a current or former Affiliation.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Admissions Review</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Declined Offer</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Lost Opportunity</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Applicant__c.field-meta.xml
<CustomField>
    <fullName>traa_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact record of the applicant</description>
    <inlineHelpText>Lookup to the contact record of the applicant</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Is_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>traa_Is_Enrollment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field stores true value, when an opportunity is created and the record type is an enrollment based.</description>
    <inlineHelpText>This field stores true value, when an opportunity is created and the record type is an enrollment based.</inlineHelpText>
    <label>Is Enrollment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies primary academic program affiliation record</description>
    <inlineHelpText>Identifies primary academic program affiliation record</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Enrollment_Record_Types__mdt/traa_Opportunity_Enrollment_Record_Types__mdt.object-meta.xml
<CustomObject>
    <description>This metadata table would hold data to identify Opportunity Record Types that fall under the Enrollment Process</description>
    <label>Opportunity Enrollment Record Type</label>
    <pluralLabel>Opportunity Enrollment Record Types</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Opportunity_Enrollment_Record_Types__mdt/fields/traa_Is_Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>traa_Is_Enrollment_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox would identify if Opportunity is an Enrollment type</description>
    <label>Is Enrollment Type</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Enrollment_Record_Types__mdt/fields/traa_RecordType_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>traa_RecordType_Developer_Name__c</fullName>
    <description>This will hold Record Type&#39;s Developer Name</description>
    <inlineHelpText>This will hold Record Type&#39;s Developer Name</inlineHelpText>
    <label>RecordType Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Enrollment_Record_Types__mdt/fields/traa_RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>traa_RecordType_Name__c</fullName>
    <description>This will hold Record Type&#39;s Name</description>
    <inlineHelpText>This will hold Record Type&#39;s Name</inlineHelpText>
    <label>RecordType Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/traa_AffiliationStatusUpdate_TDTMTest.cls
/**
* @description Test class for traa_AffiliationStatusUpdate_TDTM
*
*
* @author      Traction on Demand (Traction TRAA Package)
* @date        2020-02-28
*/

@isTest
public class traa_AffiliationStatusUpdate_TDTMTest {
    @isTest
    private static void affiliationStatusUpdateTest(){
        
        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        
        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_AffiliationCreate_TDTM', 'Opportunity', 'AfterInsert', 1.00));
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_AffiliationStatusUpdate_TDTM', 'Opportunity', 'AfterUpdate', 1.00));
        
       	
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
        
        List<RecordType> recordTypeList = new List<RecordType>();
        
        //Create Account Record
        Account account = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,  true);
        
        //Create Academic Program Record
        Id recordTypeIdAcc = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        Map<String, Object> academicProgramAdditionalFields = new Map<String, Object>{
            'RecordTypeId' => recordTypeIdAcc
                }; 
         Account academicProgram = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,academicProgramAdditionalFields,  true);
        
        Map<String, Object> contactAdditionalFields = new Map<String, Object>{
            'AccountId'       => account.Id
                };
                    
        //Create Contact Record
        Contact contact = (Contact) tf_TestFactory.createSObject(tf_ContactWrapper.class, contactAdditionalFields, true);
        
        //Fetch Enrollment Recordtype Id
        List<Id> recordTypeIds = new List<Id>();
        //Get Enrollment Type Record Types of Opportunity from Metadata table
        for (traa_Opportunity_Enrollment_Record_Types__mdt metadataRules : [
            SELECT Id, traa_Is_Enrollment_Type__c, traa_RecordType_Developer_Name__c, traa_RecordType_Name__c
            FROM traa_Opportunity_Enrollment_Record_Types__mdt
            WHERE traa_Is_Enrollment_Type__c = :TRUE
        ]) {
            recordTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(metadataRules.traa_RecordType_Developer_Name__c).getRecordTypeId());
        }
            
        Map<String, Object> opportunityAdditionalFields = new Map<String, Object>{
            'traa_Applicant__c'       => contact.Id,
                'AccountId' 		=> account.Id,
                'traa_Academic_Program__c' => academicProgram.Id,
                'RecordTypeId' => recordTypeIds[0],
                'traa_Is_Enrollment__c' => true
                };
        
         //Create Opportunity Record
         Opportunity opp = (Opportunity) tf_TestFactory.createSObject(tf_OpportunityWrapper.class,  opportunityAdditionalFields, true);
        
        test.startTest();
        //Update Opportunity Record
        opp.StageName = 'Ineligible';
        update opp;
        test.stopTest();
        
        Opportunity insertedOpprtunity = [SELECT Id, stagename, traa_Primary_Affiliation__r.hed__Status__c from Opportunity WHERE Id =: opp.Id];
        System.assertEquals('Lost Opportunity', insertedOpprtunity.traa_Primary_Affiliation__r.hed__Status__c, 'Affiliation Status is not updated');
    }
}