unpackaged/main/default/objects/hed__Affiliation__c/hed__Affiliation__c.object-meta.xml
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Affiliation__c/fields/traa_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>traa_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the initial opportunity that led to the affiliation being created</description>
    <inlineHelpText>Lookup to the initial opportunity that led to the affiliation being created</inlineHelpText>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.traa_Is_Enrollment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>traa_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Affiliation__c/fields/traa_Primary_at_Recruitment__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_at_Recruitment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this was the primary academic degree affiliation when the student entered the recruitment cycle of the program.</description>
    <inlineHelpText>Indicates this was the primary academic degree affiliation when the student entered the recruitment cycle of the program.</inlineHelpText>
    <label>Primary at Recruitment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/hed__Affiliation__c/fields/traa_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>traa_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Program Enrollment Record</description>
    <inlineHelpText>Lookup to Program Enrollment Record</inlineHelpText>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>traa_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&#39;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Program_Enrollment__c/fields/hed__Affiliation__c.field-meta.xml
<CustomField>
    <fullName>hed__Affiliation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is auto-populated with the Affiliation record that represents the student&#39;s enrollment in this Program.</description>
    <inlineHelpText>This field is auto-populated with the Affiliation record that represents the student&#39;s enrollment in this Program.</inlineHelpText>
    <label>Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/hed__Program_Enrollment__c/fields/hed__Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Enrollment_Status__c</fullName>
    <description>The student&#39;s enrollment status, for example, full-time or half-time.</description>
    <inlineHelpText>The student&#39;s enrollment status, for example, full-time or half-time.</inlineHelpText>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Half-time</fullName>
            </value>
            <value>
                <fullName>Less than half-time</fullName>
            </value>
            <value>
                <fullName>Enrolled-Not Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/hed__Program_Enrollment__c/fields/traa_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>traa_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to original opportunity</description>
    <inlineHelpText>Lookup to original opportunity</inlineHelpText>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.traa_Is_Enrollment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>traa_Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Applicant__c.field-meta.xml
<CustomField>
    <fullName>traa_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact record of the applicant</description>
    <inlineHelpText>Lookup to the contact record of the applicant</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Dual_Degree_Sec_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Dual_Degree_Sec_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the secondary Academic Program, in case of dual degree program during application.</inlineHelpText>
    <label>Dual Degree Secondary Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dual Sec: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>traa_Secondary_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies primary academic program affiliation record</description>
    <inlineHelpText>Identifies primary academic program affiliation record</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Secondary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>traa_Secondary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Opportunities (Secondary Affiliation)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Secondary_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>traa_Secondary_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities (Secondary Program Enrollment)</relationshipLabel>
    <relationshipName>traa_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/traa_Opportunity_Stage__mdt.object-meta.xml
<CustomObject>
    <description>This metadata table would hold data to identify Opportunity Stage that will count as &quot;Enrolled&quot;.</description>
    <label>Opportunity Stage</label>
    <pluralLabel>Opportunity Stages</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/fields/Opp_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Opp_Stage_Name__c</fullName>
    <description>Stage name of the Opportunity</description>
    <inlineHelpText>Stage Name of the Opportunity</inlineHelpText>
    <label>Opp Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/fields/traa_Count_as_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>traa_Count_as_Enrolled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, then count stage as enrolled otherwise not.</description>
    <label>Count as Enrolled?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/traa_ProgramEnrollmentCreate_TDTM.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Trigger to automatically create the program enrollment on an opportunity stage change to Close Won status.
*/

global without sharing class traa_ProgramEnrollmentCreate_TDTM extends hed.TDTM_Runnable {
    // the main entry point for TDTM to invoke our trigger handlers.

    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

        Map<Id, Opportunity> oppEnrollmentMap = new Map<Id, Opportunity>();

        if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>((List<Opportunity>) oldList);
            processOpportunityStageNameUpdate((List<Opportunity>) newList, oldMap);
        }
        return dmlWrapper;
    }
    //Return Program Enrollment list for Opportunities Whose Stage is Closed Won
    private List<hed__Program_Enrollment__c> createProgramEnrollments(List<Opportunity> oppEnrollments) {
        List<hed__Program_Enrollment__c> programEnrollmentList = new List<hed__Program_Enrollment__c>();

        for (Opportunity oppObject : oppEnrollments) {
            //Create Program Enrollment Records for Opportunities Whose Stage is Closed Won
            hed__Program_Enrollment__c programEnrollment = new hed__Program_Enrollment__c();
            programEnrollment.traa_Opportunity__c = oppObject.Id;
            programEnrollment.hed__Account__c = oppObject.traa_Academic_Program__c;
            programEnrollment.hed__Admission_Date__c = System.today();
            programEnrollment.hed__Affiliation__c = oppObject.traa_Primary_Affiliation__c;
            programEnrollment.hed__Enrollment_Status__c = oppObject.StageName;
            programEnrollment.hed__Contact__c = oppObject.traa_Applicant__c;
            programEnrollmentList.add(programEnrollment);
            if (oppObject.traa_Secondary_Affiliation__c != null && oppObject.traa_Dual_Degree_Sec_Academic_Program__c != null) {
                hed__Program_Enrollment__c secondaryProgramEnrollment = programEnrollment.clone();
                secondaryProgramEnrollment.hed__Affiliation__c = oppObject.traa_Secondary_Affiliation__c;
                secondaryProgramEnrollment.hed__Account__c = oppObject.traa_Dual_Degree_Sec_Academic_Program__c;
                programEnrollmentList.add(secondaryProgramEnrollment);
            }
        }
        return programEnrollmentList;
    }

    private void processOpportunityStageNameUpdate(List<Opportunity> opportunities, Map<id, opportunity> oldMap) {
        Set<String> stageNames = new Set<String>(getStages());
        Map<Id, opportunity> opportunityMap = new Map<Id, opportunity>();
        Map<Id, hed__Program_Enrollment__c> programEnrollmentMap = new Map<Id, hed__Program_Enrollment__c>();
        List<hed__Program_Enrollment__c> programEnrollmentList = new List<hed__Program_Enrollment__c>();
        Map<Id, hed__Program_Enrollment__c> affiliationToProgEnrollmentMap = new Map<Id, hed__Program_Enrollment__c>();
        Map<Id, Id> progEnrollmentToOppIdsMap = new Map<Id, Id>();
        if(!stageNames.isEmpty()) {
            for(Opportunity opportunity : opportunities) {
                if(String.isNotBlank(opportunity.StageName) && stageNames.contains(opportunity.StageName) && isStageChanged(opportunity, oldMap)) {
                    opportunityMap.put(opportunity.Id, opportunity);
                }
            }
        }
        if (!opportunityMap.isEmpty()) {
            programEnrollmentList = createProgramEnrollments(opportunityMap.values());
        }
        if (!programEnrollmentList.isEmpty()) {
            insert programEnrollmentList;
        }
        programEnrollmentMap.putAll(programEnrollmentList);
        for (hed__Program_Enrollment__c progEnrollment : programEnrollmentMap.values()) {
            affiliationToProgEnrollmentMap.put(progEnrollment.hed__Affiliation__c, progEnrollment);
            progEnrollmentToOppIdsMap.put(progEnrollment.Id, progEnrollment.traa_Opportunity__c);
        }
        updateProgramEnrollementOnOpportunity(opportunityMap, progEnrollmentToOppIdsMap, programEnrollmentMap);
        updateAffilaitions(affiliationToProgEnrollmentMap);
    }

    private void updateProgramEnrollementOnOpportunity(Map<Id, Opportunity> opportunityMap, Map<Id, Id> progEnrollmentToOppIdsMap, Map<Id, hed__Program_Enrollment__c> programEnrollmentMap) {
        Map<Id, Opportunity> progEnrollmentIdToOppUpdateMap = new Map<Id, Opportunity>();
        for (Id progEnrId : progEnrollmentToOppIdsMap.keySet()) {
            Opportunity opp = progEnrollmentIdToOppUpdateMap.containsKey(progEnrollmentToOppIdsMap.get(progEnrId)) ? progEnrollmentIdToOppUpdateMap.get(progEnrollmentToOppIdsMap.get(progEnrId)) : new Opportunity();
            opp.Id = progEnrollmentToOppIdsMap.get(progEnrId);
            if (opportunityMap.containsKey(opp.Id) && opportunityMap.get(opp.Id).traa_Secondary_Affiliation__c == programEnrollmentMap.get(progEnrId).hed__Affiliation__c) {
                opp.traa_Secondary_Program_Enrollment__c = progEnrId;
            } else {
                opp.traa_Primary_Program_Enrollment__c = progEnrId;
            }
            progEnrollmentIdToOppUpdateMap.put(opp.Id, opp);
        }
        if(!progEnrollmentIdToOppUpdateMap.isEmpty()) {
            update progEnrollmentIdToOppUpdateMap.values();
        }
    }

    private void updateAffilaitions( Map<Id, hed__Program_Enrollment__c> affiliationToProgEnrollmentMap) {
        List<hed__Affiliation__c> affiliationsToUpdate = new List<hed__Affiliation__c>();
        for (hed__Affiliation__c affiliation : [SELECT Id, traa_Primary_at_Recruitment__c, traa_Program_Enrollment__c FROM hed__Affiliation__c WHERE Id IN :affiliationToProgEnrollmentMap.keySet()]) {
            affiliation.traa_Program_Enrollment__c = affiliationToProgEnrollmentMap.get(affiliation.Id).Id;
            affiliation.hed__Primary__c = true;
            affiliationsToUpdate.add(affiliation);
        }
        if(!affiliationsToUpdate.isEmpty()) {
            update affiliationsToUpdate;
        }
    }

    private Boolean isStageChanged(Opportunity opportunity, Map<id, opportunity> oldMap) {
        return (oldMap != null && opportunity.StageName != oldMap.get(opportunity.Id).StageName);
    }

    private Set<String> getStages() {
        Set<String> stageNames = new Set<String>();
        for(traa_Opportunity_Stage__mdt metadataRules : [SELECT Id, Opp_Stage_Name__c, traa_Count_as_Enrolled__c FROM traa_Opportunity_Stage__mdt WHERE traa_Count_as_Enrolled__c = :true]) {
            if(String.isNotBlank(metadataRules.Opp_Stage_Name__c)) {
                stageNames.add(metadataRules.Opp_Stage_Name__c);
            }
        }
        return stageNames;
    }
}