unpackaged/main/default/objects/hed__Affiliation__c/hed__Affiliation__c.object-meta.xml
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Affiliation__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Indicates whether this is a current or former Affiliation.</description>
    <inlineHelpText>Indicates whether this is a current or former Affiliation.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Admissions Review</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Declined Offer</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Lost Opportunity</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>traa_Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies primary academic program affiliation record</description>
    <inlineHelpText>Identifies primary academic program affiliation record</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/traa_Status_Processor_Rule__mdt.object-meta.xml
<CustomObject>
    <description>Designed to automate the transition of record statuses.</description>
    <label>traa Status Processor Rule</label>
    <pluralLabel>traa Status Processor Rules</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_Field__c</fullName>
    <label>Source Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_SObject_Type__c</fullName>
    <label>Source SObject Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Source_Value__c.field-meta.xml
<CustomField>
    <fullName>traa_Source_Value__c</fullName>
    <label>Source Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>traa_Target_Field__c</fullName>
    <label>Target Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Target_Reference__c.field-meta.xml
<CustomField>
    <fullName>traa_Target_Reference__c</fullName>
    <label>Target Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Status_Processor_Rule__mdt/fields/traa_Target_Value__c.field-meta.xml
<CustomField>
    <fullName>traa_Target_Value__c</fullName>
    <label>Target Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/traa_StatusProcessorTest.cls
@IsTest
public class traa_StatusProcessorTest {
    private static final String SA_SOURCE_STAGE = 'Admissions';
    private static final String SA_TARGET_STATUS = 'Completed';
    
    static {
        traa_StatusProcessor.rules = (List<traa_Status_Processor_Rule__mdt>) JSON.deserialize(
            JSON.serialize(new List<Map<String, String>>{
                // Standard Rules
                new Map<String, String>{
                    'Id'                     => '1',
                        'traa_Source_SObject_Type__c' => 'Opportunity',
                        'traa_Source_Field__c'        => 'StageName',
                        'traa_Source_Value__c'        => SA_SOURCE_STAGE,
                        'traa_Target_Reference__c'    => 'traa_Primary_Affiliation__r.Id',
                        'traa_Target_Field__c'        => 'hed__Status__c',
                        'traa_Target_Value__c'        => SA_TARGET_STATUS
                        }
            }),
            List<traa_Status_Processor_Rule__mdt>.class
        );
    }
    
    @isTest
    private static void testStandard() {
        
        hed__Affiliation__c affiliation = new hed__Affiliation__c();
        affiliation.hed__Status__c = 'Enrolled';
        insert affiliation;
        
        Opportunity oppt = (Opportunity)tf_TestFactory.createSObject(tf_OpportunityWrapper.class, true);
        Map<ID,Opportunity> oldMap = new Map<ID,Opportunity>([SELECT Id,StageName,RecordTypeId,traa_Primary_Affiliation__c FROM Opportunity WHERE Id =:oppt.Id]);
        oppt.StageName = SA_SOURCE_STAGE;
        oppt.traa_Primary_Affiliation__c = affiliation.Id;
        update oppt;
        
        Test.startTest();
        List<SObject> sObjects = new List<SObject>();
        sObjects.add(oppt);
        traa_StatusProcessor.execute(sObjects, oldMap);
        Test.stopTest();
        hed__Affiliation__c affl = [SELECT hed__Status__c FROM hed__Affiliation__c WHERE Id = :affiliation.Id].get(0);
        System.assertEquals(SA_TARGET_STATUS, affl.hed__Status__c);
    }
    
}