unpackaged/main/default/objects/Lead/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <label>Academic Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master of Education</fullName>
            </value>
            <value>
                <fullName>Master of Arts in Special Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Area_of_Interest__c</fullName>
    <label>Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Nursing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Level__c.field-meta.xml
<CustomField>
    <fullName>traa_Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Bachelor</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Doctoral</fullName>
            </value>
            <value>
                <fullName>Non-Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Program_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Program_of_Interest__c</fullName>
    <description>This field is used to capture the primary program of interest of a lead. There should only be one program of interest that corresponds to an Academic Program&#39;s Admissions Cycle.</description>
    <inlineHelpText>Used to capture one academic program admissions cycle account record. The free-form text must match a academic program account record to automatically populate  the academic program of an opportunity on lead conversion.</inlineHelpText>
    <label>Program of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Start_Term__c.field-meta.xml
<CustomField>
    <fullName>traa_Start_Term__c</fullName>
    <label>Start Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2237</fullName>
            </value>
            <value>
                <fullName>2243</fullName>
            </value>
            <value>
                <fullName>2245</fullName>
            </value>
            <value>
                <fullName>2247</fullName>
            </value>
            <value>
                <fullName>2253</fullName>
            </value>
            <value>
                <fullName>2255</fullName>
            </value>
            <value>
                <fullName>2257</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/traa_LeadProgramOfInterestHandlerTest.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Test Class for traa_LeadProgramOfInterestHandler class
*/
@IsTest
private with sharing class traa_LeadProgramOfInterestHandlerTest {
    @testSetup static void setup() {
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_LeadProgramOfInterestHandler', 'Lead', 'BeforeInsert, BeforeUpdate', 1.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);
    }

    @IsTest
    static void onBeforeInsert() {
        Lead lead = new Lead(
            LastName = 'Doe',
            FirstName = 'John',
            Company = 'Test',
            Status = 'New',
            traa_Academic_Program__c = 'Master of Education',
            traa_Area_of_Interest__c = 'Business',
            traa_Level__c = 'Certificate',
            traa_Start_Term__c = '2237',
            Email = 'test123@test.com'
        );

        Test.startTest();
        insert lead;
        Test.stopTest();
        Lead updatedLead = getLead();
        System.assertEquals('Master of Education-2237', updatedLead.traa_Program_of_Interest__c, 'Program of interest should match');
    }

    @IsTest
    static void onBeforeAcedemicProgramUpdate() {
        Lead lead = new Lead(
            LastName = 'Doe',
            FirstName = 'John',
            Company = 'Test',
            Status = 'New',
            traa_Academic_Program__c = 'Master of Education',
            traa_Area_of_Interest__c = 'Business',
            traa_Level__c = 'Certificate',
            traa_Start_Term__c = '2237',
            Email = 'test123@test.com'
        );
        insert lead;
        Test.startTest();
        Lead updateLead = getLead();
        updateLead.traa_Academic_Program__c = 'Master of Arts in Special Education';
        update updateLead;
        Test.stopTest();
        Lead updatedLeadRecord = getLead();
        System.assertEquals('Master of Arts in Special Education-2237', updatedLeadRecord.traa_Program_of_Interest__c, 'Program of interest should match');
    }

    @IsTest
    static void onBeforeTermUpdate() {
        Lead lead = new Lead(
            LastName = 'Doe',
            FirstName = 'John',
            Company = 'Test',
            Status = 'New',
            traa_Academic_Program__c = 'Master of Education',
            traa_Area_of_Interest__c = 'Business',
            traa_Level__c = 'Certificate',
            traa_Start_Term__c = '2237',
            Email = 'test123@test.com'
        );
        insert lead;
        Test.startTest();
        Lead updateLead = getLead();
        updateLead.traa_Start_Term__c = '2243';
        update updateLead;
        Test.stopTest();
        Lead updatedLeadRecord = getLead();
        System.assertEquals('Master of Education-2243', updatedLeadRecord.traa_Program_of_Interest__c, 'Program of interest should match');
    }

    @IsTest
    static void onBeforeLevelUpdate() {
        Lead lead = new Lead(
            LastName = 'Doe',
            FirstName = 'John',
            Company = 'Test',
            Status = 'New',
            traa_Academic_Program__c = 'Master of Education',
            traa_Area_of_Interest__c = 'Business',
            traa_Level__c = 'Certificate',
            traa_Start_Term__c = '2237',
            Email = 'test123@test.com'
        );
        insert lead;
        Test.startTest();
        Lead updateLead = getLead();
        updateLead.traa_Level__c = 'Bachelor';
        update updateLead;
        Test.stopTest();
        Lead updatedLeadRecord = getLead();
        System.assertEquals('Master of Education-2237', updatedLeadRecord.traa_Program_of_Interest__c, 'Program of interest should match');
    }

    private  static Lead getLead() {
        return [SELECT Id, traa_Academic_Program__c, traa_Program_of_Interest__c, traa_Start_Term__c FROM Lead WHERE Email = 'test123@test.com' LIMIT 1];
    }
}