unpackaged/main/default/objects/Lead/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <label>Academic Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master of Education</fullName>
            </value>
            <value>
                <fullName>Master of Arts in Special Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Other_Program_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Other_Program_of_Interest__c</fullName>
    <inlineHelpText>Used to capture other academic program admissions cycle account records, other than Program Of Interest. The picklist value must match an academic program account record to automatically populate the Other academic program on the opportunity on lead conversion.</inlineHelpText>
    <label>Other Program of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Program_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Program_of_Interest__c</fullName>
    <description>This field is used to capture the primary program of interest of a lead. There should only be one program of interest that corresponds to an Academic Program&#39;s Admissions Cycle.</description>
    <inlineHelpText>Used to capture one academic program admissions cycle account record. The free-form text must match a academic program account record to automatically populate  the academic program of an opportunity on lead conversion.</inlineHelpText>
    <label>Program of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the primary Academic Program during application.</description>
    <inlineHelpText>Lookup to the primary Academic Program during application.</inlineHelpText>
    <label>Academic Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Acad Program: Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>traa_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/traa_Other_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Other_Academic_Program__c</fullName>
    <description>Picklist to the other Academic Program selected during application.</description>
    <inlineHelpText>Picklist to the other Academic Program selected during application.</inlineHelpText>
    <label>Other Academic Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Other Academic Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/traa_LeadConversionPOI_TDTMTest.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Test Class for traa_LeadConversionPOI_TDTM class
*/
@IsTest
private class traa_LeadConversionPOI_TDTMTest {

    @IsTest
    static void testBehavior() {
        //Retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        //Create trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('traa_LeadConversionPOI_TDTM', 'Lead', 'AfterUpdate', 1.00));

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        //Create Account Record
        Id recordTypeIdAcc = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(traa_Constants.RT_ACADEMIC_PROGRAM).getRecordTypeId();
        Account account1 = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,  false);
        account1.RecordTypeId = recordTypeIdAcc;
        String accountName1 = account1.Name;
        Account account2 = (Account) tf_TestFactory.createSObject(tf_AccountWrapper.class,  false);
        account2.RecordTypeId = recordTypeIdAcc;
        String accountName2 = account2.Name;
        insert new List<Account>{account1, account2};

        Lead lead = new Lead(
                LastName = 'Doe',
                FirstName = 'John',
                Company = 'Test',
                Status = 'New',
                traa_Program_of_Interest__c = accountName1,
                traa_Other_Program_of_Interest__c = accountName2);
        insert lead;

        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(lead.Id);
        lc.setDoNotCreateOpportunity(false);
        lc.setConvertedStatus('Converted');

        Test.startTest();
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        Test.stopTest();
        System.assert(lcr.isSuccess());

        List<Opportunity> opportunities = new List<Opportunity>();
        opportunities = [SELECT Id, traa_Academic_Program__c, traa_Academic_Program__r.Name, traa_Other_Academic_Program__c FROM Opportunity];
        System.assert(opportunities.size() == 1);
        System.assert(opportunities[0].traa_Academic_Program__r.Name == accountName1);
        System.assertEquals(opportunities[0].traa_Other_Academic_Program__c,lead.traa_Other_Program_of_Interest__c, 'Other Academic Program not filled on opportunity based on the Lead.');
    }

}