unpackaged/main/default/objects/Opportunity/fields/Home_Campus__c.field-meta.xml
<CustomField>
    <fullName>Home_Campus__c</fullName>
    <label>Home Campus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hialeah</fullName>
                <label>Hialeah Campus</label>
            </value>
            <value>
                <fullName>Homestead</fullName>
                <label>Homestead Campus</label>
            </value>
            <value>
                <fullName>Padron</fullName>
                <label>Padron Campus</label>
            </value>
            <value>
                <fullName>Kendall</fullName>
                <label>Kendall Campus</label>
            </value>
            <value>
                <fullName>Medical</fullName>
                <label>Medical Campus</label>
            </value>
            <value>
                <fullName>North</fullName>
                <label>North Campus</label>
            </value>
            <value>
                <fullName>West</fullName>
                <label>West Campus</label>
            </value>
            <value>
                <fullName>Wolfson</fullName>
                <label>Wolfson Campus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PCA_Assignment_trigger__c.field-meta.xml
<CustomField>
    <fullName>PCA_Assignment_trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in automation to trigger automatic assignment of PCAs</description>
    <label>PCA Assignment trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_PCA__c.field-meta.xml
<CustomField>
    <fullName>Primary_PCA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary PCA Advisor</description>
    <inlineHelpText>Primary PCA Advisor</inlineHelpText>
    <label>Primary PCA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Student_Onboarding_Type__c.field-meta.xml
<CustomField>
    <fullName>Student_Onboarding_Type__c</fullName>
    <label>Student Onboarding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTIC - Direct Entry</fullName>
                <label>Direct-Entry</label>
            </value>
            <value>
                <fullName>FTIC - Traditional (under 25 not Direct Entry)</fullName>
                <label>Traditional</label>
            </value>
            <value>
                <fullName>FTIC Non-Traditional (25 and older)</fullName>
                <label>Non-Traditional</label>
            </value>
            <value>
                <fullName>Non-FTIC</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>FTIC Non-Degree</fullName>
                <label>Non-Degree</label>
            </value>
            <value>
                <fullName>DUAL EN.</fullName>
                <label>Dual Enrollment</label>
            </value>
            <value>
                <fullName>INT.</fullName>
                <label>International</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/PCA_Assigned_Home_Campus__c.field-meta.xml
<CustomField>
    <fullName>PCA_Assigned_Home_Campus__c</fullName>
    <label>PCA Assigned Home Campus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hialeah</fullName>
                <label>Hialeah Campus</label>
            </value>
            <value>
                <fullName>Homestead</fullName>
                <label>Homestead Campus</label>
            </value>
            <value>
                <fullName>Kendall</fullName>
                <label>Kendall Campus</label>
            </value>
            <value>
                <fullName>Medical</fullName>
                <label>Medical Campus</label>
            </value>
            <value>
                <fullName>North</fullName>
                <label>North Campus</label>
            </value>
            <value>
                <fullName>Padron</fullName>
                <label>Padron Campus</label>
            </value>
            <value>
                <fullName>West</fullName>
                <label>West Campus</label>
            </value>
            <value>
                <fullName>Wolfson</fullName>
                <label>Wolfson Campus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityRTFAutoAssignTest.cls
@istest
public class OpportunityRTFAutoAssignTest {
 @testSetup
    static void setupTestData() {
        // Ensure these values match exactly with the values in Salesforce
        String validPicklistValue1 = 'Hialeah'; // Example valid value from your picklist
        String validPicklistValue2 = 'Homestead';   // Another example valid value

        // Create Users with different Home Campus and Active status
        User user1 = new User(
            FirstName = 'User',
            LastName = 'One',
            Email = 'user1@example.com',
            Username = 'user1@example.com.' + System.currentTimeMillis(),
            Alias = 'uone',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            LanguageLocaleKey = 'en_US',
            PCA_Assigned_Home_Campus__c = validPicklistValue1,
            IsActive = true
        );
        User user2 = new User(
            FirstName = 'User',
            LastName = 'Two',
            Email = 'user2@example.com',
            Username = 'user2@example.com.' + System.currentTimeMillis(),
            Alias = 'utwo',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            LanguageLocaleKey = 'en_US',
            PCA_Assigned_Home_Campus__c = validPicklistValue2,
            IsActive = true
        );
        insert new List<User>{user1, user2};

        // Create Opportunities with valid Home Campus values
        Opportunity opp1 = new Opportunity(
            Name = 'Opportunity 1',
            StageName = 'Lead',
            CloseDate = Date.today(),
            PCA_Assignment_trigger__c = true,
            Home_Campus__c = validPicklistValue1,Student_Onboarding_Type__c= 'FTIC - Direct Entry',Primary_PCA__c = user1.Id
        );
        Opportunity opp2 = new Opportunity(
            Name = 'Opportunity 2',
            StageName = 'Applicant',
            CloseDate = Date.today(),
            PCA_Assignment_trigger__c = true,
            Home_Campus__c = validPicklistValue2,Student_Onboarding_Type__c= 'FTIC - Direct Entry',Primary_PCA__c = user1.Id
        );
        insert new List<Opportunity>{opp1, opp2};
    }
@isTest
    static void updateOppCounttest() {
		List<Opportunity> oppList = [select id,Name,StageName,closeDate,PCA_Assignment_trigger__c,Home_Campus__c,Primary_PCA__c,Student_Onboarding_Type__c from opportunity];
		List<User> userList = [select id,PCA_Assigned_Home_Campus__c,IsActive from user];
		List<OpportunityRTFAutoAssign.inputs> inputList = new List<OpportunityRTFAutoAssign.inputs>();
		OpportunityRTFAutoAssign.inputs inputRec1 = new OpportunityRTFAutoAssign.inputs();
		system.debug('oppList'+oppList);
		system.debug('userList'+userList);
		inputRec1.homeCampusOpps = userList;
		inputRec1.opp = oppList[1];
		inputList.add(inputRec1);
		Test.StartTest();
       List<OpportunityRTFAutoAssign.outputs> outpulist =  OpportunityRTFAutoAssign.updateOppCount(inputList);
		Test.StopTest();
	}
}