unpackaged/main/default/objects/Opportunity/fields/Primary_PCA__c.field-meta.xml
<CustomField>
    <fullName>Primary_PCA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary PCA Advisor</description>
    <inlineHelpText>Primary PCA Advisor</inlineHelpText>
    <label>Primary PCA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Student_Onboarding_Type__c.field-meta.xml
<CustomField>
    <fullName>Student_Onboarding_Type__c</fullName>
    <label>Student Onboarding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTIC - Direct Entry</fullName>
                <label>Direct-Entry</label>
            </value>
            <value>
                <fullName>FTIC - Traditional (under 25 not Direct Entry)</fullName>
                <label>Traditional</label>
            </value>
            <value>
                <fullName>FTIC Non-Traditional (25 and older)</fullName>
                <label>Non-Traditional</label>
            </value>
            <value>
                <fullName>Non-FTIC</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>FTIC Non-Degree</fullName>
                <label>Non-Degree</label>
            </value>
            <value>
                <fullName>DUAL EN.</fullName>
                <label>Dual Enrollment</label>
            </value>
            <value>
                <fullName>INT.</fullName>
                <label>International</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityRTFAutoAssign.cls
public class OpportunityRTFAutoAssign {
    @InvocableMethod
    public static List<outputs> updateOppCount(List<inputs> inputList){
        Set<Id> userIds = new Set<Id>();
        Map<Id,List<Opportunity>> userOppMap = new Map<Id,List<Opportunity>>();
        Integer oppCountval = 15000;
        List<outputs> outputInfo = new List<outputs>();
        for(inputs inVal:inputList){
            for(User u:inVal.homeCampusOpps){
                userIds.add(u.Id);
            }
        }
        
        for(opportunity oppRec:[select id,Primary_PCA__c from opportunity where Primary_PCA__c IN:userIds AND ( StageName ='Lead' OR StageName ='Applicant' OR StageName ='Enrolled-Not Paid' ) AND Student_Onboarding_Type__c = 'FTIC - Direct Entry' ]){
            if(userOppMap!=null && userOppMap.containskey(oppRec.Primary_PCA__c)){
                List<Opportunity> tempMap = userOppMap.get(oppRec.Primary_PCA__c);
                tempMap.add(oppRec);
                userOppMap.put(oppRec.Primary_PCA__c,tempMap);
            }
            else{
                userOppMap.put(oppRec.Primary_PCA__c,new List<opportunity>{oppRec});
            }
        }
        system.debug('userOppMap'+userOppMap);
        system.debug('oppCountval'+oppCountval);
        system.debug('inputList'+inputList);
        for(inputs inVal:inputList){
            for(User u:inVal.homeCampusOpps){
                if(userOppMap!=null && userOppMap.get(u.id)!=null && userOppMap.get(u.id).size() < oppCountval){
                    outputs sendVals = new outputs();
                    sendVals.oppCount = userOppMap.get(u.id).size();
                    sendVals.userRec = u;
                    outputInfo.add(sendVals);
                }
                
            }
            
        }
        return outputInfo;
    }
    public class inputs{
        @InvocableVariable public List<User> homeCampusOpps;
        @InvocableVariable public opportunity opp;
    }
    public class outputs{
        @InvocableVariable public Integer oppCount;
        @InvocableVariable public User userRec;
        
    }
}