unpackaged/main/default/objects/Opportunity/fields/traa_Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>traa_Enrollment_Date__c</fullName>
    <description>Date applicant enrolled</description>
    <inlineHelpText>Date applicant enrolled</inlineHelpText>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/traa_Opportunity_Stage__mdt.object-meta.xml
<CustomObject>
    <description>This metadata table would hold data to identify Opportunity Stage that will count as &quot;Enrolled&quot;.</description>
    <label>Opportunity Stage</label>
    <pluralLabel>Opportunity Stages</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/fields/Opp_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Opp_Stage_Name__c</fullName>
    <description>Stage name of the Opportunity</description>
    <inlineHelpText>Stage Name of the Opportunity</inlineHelpText>
    <label>Opp Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/traa_Opportunity_Stage__mdt/fields/traa_Count_as_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>traa_Count_as_Enrolled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, then count stage as enrolled otherwise not.</description>
    <label>Count as Enrolled?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/traa_EnrollmentDateUpdate_TDTM.cls
/**
* @description TDTM class for Opportunity trigger
*
*
* @author      Traction on Demand (Traction TRAA Package)
* @date        2020-02-13
*/

global without sharing class traa_EnrollmentDateUpdate_TDTM extends hed.TDTM_Runnable {
    // the main entry point for TDTM to invoke our trigger handlers.
    
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        
        if (triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate) {
            Set<String> stageNames = new Set<String>();
            Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>((List<Opportunity>) oldList);
            //Get Stage Name of Opportunity from Metadata Table
            for (traa_Opportunity_Stage__mdt metadataRules : [ SELECT Id, Opp_Stage_Name__c, traa_Count_as_Enrolled__c FROM traa_Opportunity_Stage__mdt WHERE traa_Count_as_Enrolled__c =: true]) {
                stageNames.add(metadataRules.Opp_Stage_Name__c);
            }
            //Update Opportunity Enrollment Date
            if(!stageNames.isEmpty()){
                for (Opportunity oppObject : (List<Opportunity>) newList) {
                    if (String.isNotBlank(oppObject.StageName) && stageNames.contains(oppObject.StageName) &&  oldOppMap.get(oppObject.Id).StageName != oppObject.StageName) {
                        oppObject.traa_Enrollment_Date__c = System.today();
                    }
                }
            }
        }
        return dmlWrapper;
    } 
}