unpackaged/main/default/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/hed__Term__c/fields/traa_Open_for_Applications__c.field-meta.xml
<CustomField>
    <fullName>traa_Open_for_Applications__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open for Applications</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>traa_Academic_Program__c</fullName>
    <label>Academic Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master of Education</fullName>
            </value>
            <value>
                <fullName>Master of Arts in Special Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Area_of_Interest__c</fullName>
    <label>Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Nursing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Level__c.field-meta.xml
<CustomField>
    <fullName>traa_Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Bachelor</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Doctoral</fullName>
            </value>
            <value>
                <fullName>Non-Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Program_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>traa_Program_of_Interest__c</fullName>
    <description>This field is used to capture the primary program of interest of a lead. There should only be one program of interest that corresponds to an Academic Program&#39;s Admissions Cycle.</description>
    <inlineHelpText>Used to capture one academic program admissions cycle account record. The free-form text must match a academic program account record to automatically populate  the academic program of an opportunity on lead conversion.</inlineHelpText>
    <label>Program of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/traa_Start_Term__c.field-meta.xml
<CustomField>
    <fullName>traa_Start_Term__c</fullName>
    <label>Start Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2237</fullName>
            </value>
            <value>
                <fullName>2243</fullName>
            </value>
            <value>
                <fullName>2245</fullName>
            </value>
            <value>
                <fullName>2247</fullName>
            </value>
            <value>
                <fullName>2253</fullName>
            </value>
            <value>
                <fullName>2255</fullName>
            </value>
            <value>
                <fullName>2257</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/traa_LeadProgramOfInterestHandler.cls
/*
* @author          Traction on Demand (Traction TRAA Package)
* @description     Class to update program of interest on Lead 
*/
global without sharing class traa_LeadProgramOfInterestHandler extends hed.TDTM_Runnable {
    global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        List<Lead> leads = new List<Lead>((List<Lead>) newList);
        if (triggerAction == hed.TDTM_Runnable.Action.BeforeInsert) {
            populateProgramOfInterest(leads, null);
            
        }else if(triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate) {
            Map<Id, Lead> oldMap = new Map<Id, Lead>((List<Lead>) oldList);
            populateProgramOfInterest(leads, oldMap);
        }
        return dmlWrapper;
    }

    private void populateProgramOfInterest(List<Lead> leads, Map<Id, Lead> oldMap) {
        List<String> programOfInterestNameFields = new List<String>(System.Label.traa_Lead_Program_of_Interest_Naming_Convention.split('-'));
        List<hed__Term__c> openTerms = new List<hed__Term__c>(getOpenTerms());
        for(Lead lead : leads) {
            if(oldMap == null || (isAcademicProgramChanged(lead, oldMap) || isAreaOfInteresChanged(lead, oldMap) || isStartTermChanged(lead, oldMap) || isLevelChanged(lead, oldMap))) {
                if(String.isNotBlank(lead.traa_Academic_Program__c)) {
                    if(String.isNotBlank(lead.traa_Start_Term__c)) {
                        lead.traa_Program_of_Interest__c = lead.get(programOfInterestNameFields[0])+'-'+((String)lead.get(programOfInterestNameFields[1])).toUpperCase();
                    }
                    else {
                        if(!openTerms.isEmpty()) {
                            lead.traa_Program_of_Interest__c = lead.traa_Academic_Program__c+' - '+openTerms[0].Name.toUpperCase();
                        }
                    }
                }
            }
        }
    }

    private Boolean isAcademicProgramChanged(Lead lead, Map<Id, Lead> oldMap) {
        return (oldMap != null && lead.traa_Academic_Program__c != oldMap.get(lead.Id).traa_Academic_Program__c);
    }

    private Boolean isAreaOfInteresChanged(Lead lead, Map<Id, Lead> oldMap) {
        return (oldMap != null && lead.traa_Area_of_Interest__c != oldMap.get(lead.Id).traa_Area_of_Interest__c);
    }

    private Boolean isStartTermChanged(Lead lead, Map<Id, Lead> oldMap) {
        return (oldMap != null && lead.traa_Start_Term__c != oldMap.get(lead.Id).traa_Start_Term__c);
    }

    private Boolean isLevelChanged(Lead lead, Map<Id, Lead> oldMap) {
        return (oldMap != null && lead.traa_Level__c != oldMap.get(lead.Id).traa_Level__c);
    }

    private List<hed__Term__c> getOpenTerms() {
        List<hed__Term__c> openTerms = new List<hed__Term__c>([SELECT Id, Name FROM hed__Term__c WHERE traa_Open_for_Applications__c = true]);
        return openTerms;
    }

}